### ISSUE TITLE
Invalid device id

### ISSUE THREAD

**Issue by rahilwazir** [torralba-lab/im2recipe-Pytorch#11]
I'm facing the following issue, when running the pretrained model

```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 176, in <module>
    main()
  File "test.py", line 31, in main
    model.visionMLP = torch.nn.DataParallel(model.visionMLP, device_ids=[0,1,2,3])
  File "/home/foodvision/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 111, in __init__
    _check_balance(self.device_ids)
  File "/home/foodvision/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 17, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/home/foodvision/anaconda3/envs/py27/lib/python2.7/site-packages/torch/cuda/__init__.py", line 292, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
```
CUDA `device_count` output is

```
$ torch.cuda.device_count()
1L
```

Output of `nvidia-smi`

```
$ nvidia-smi
Tue Nov 20 12:19:10 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 000023D3:00:00.0 Off |                    0 |
| N/A   35C    P0    73W / 149W |      0MiB / 11441MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Any help would be appreciated. Thanks

**Comment by rahilwazir** [comment]
Ah never mind, I had only one GPU so needed to adjust the `device_ids` to `[0]` in [test.py](https://github.com/torralba-lab/im2recipe-Pytorch/blob/master/test.py#L31)

**Comment by Malithi-gif** [comment]
@rahilwazir are you resolve this?
