### ISSUE TITLE
expected scalar type Float but found Long

### ISSUE THREAD

**Issue by rahilwazir** [torralba-lab/im2recipe-Pytorch#12]
I get the following error when training the model

```
$ python train.py --batch_size 80                                                                                                                                                    [900/1419]
There are 2 parameter groups
Initial base params lr: 0.000100
Initial vision params lr: 0.000000
/home/foodvision/anaconda3/envs/py27/lib/python2.7/site-packages/torchvision-0.2.1-py2.7.egg/torchvision/transforms/transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize inst$
ad.
Training loader prepared.
Validation loader prepared.
Traceback (most recent call last):
  File "train.py", line 372, in <module>
    main()
  File "train.py", line 115, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "train.py", line 181, in train
    cos_loss = criterion[0](output[0], output[1], target_var[0])
  File "/home/foodvision/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/foodvision/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/modules/loss.py", line 950, in forward
    return F.cosine_embedding_loss(input1, input2, target, margin=self.margin, reduction=self.reduction)
  File "/home/foodvision/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/functional.py", line 1794, in cosine_embedding_loss
    return torch.cosine_embedding_loss(input1, input2, target, margin, reduction)
RuntimeError: expected scalar type Float but found Long
```

Check this if its related: #11

**Comment by nhynes** [comment]
Thanks for the bug report! Are you running any custom modifications (e.g., to the data loader)? All of `input1`, `input2`, `target`, and `margin` should be `Float`. If you're using your own loader, you might have your `target`s coming out as `Long`s (numpy will automatically make an array of integers a `Long`).

Otherwise, can you print out the types of those tensors to help isolate which one is problematic?

**Comment by nhynes** [comment]
try `target.float()`

**Comment by rahilwazir** [comment]
OK, looks like its working

<details>
<summary>Log</summary>

```
...
(tensor([[ 0.0171,  0.0479, -0.0278,  ..., -0.0149,  0.0134, -0.0118],
        [ 0.0171,  0.0479, -0.0278,  ..., -0.0149,  0.0134, -0.0118],
        [ 0.0171,  0.0479, -0.0278,  ..., -0.0149,  0.0134, -0.0118],
        ...,
        [ 0.0171,  0.0479, -0.0278,  ..., -0.0149,  0.0134, -0.0118],
        [ 0.0171,  0.0479, -0.0278,  ..., -0.0149,  0.0134, -0.0118],
        [ 0.0171,  0.0479, -0.0278,  ..., -0.0149,  0.0134, -0.0118]],
       device='cuda:0', grad_fn=<DivBackward1>), tensor([[-0.0164,  0.0010,  0.0179,  ...,  0.0239,  0.0155, -0.0108],
        [-0.0168, -0.0081,  0.0082,  ...,  0.0314,  0.0229, -0.0231],
        [-0.0103, -0.0157,  0.0082,  ...,  0.0318,  0.0201, -0.0087],
        ...,
        [-0.0102,  0.0122,  0.0219,  ...,  0.0294,  0.0231, -0.0045],
        [-0.0188,  0.0136,  0.0153,  ...,  0.0199,  0.0130,  0.0095],
        [ 0.0036,  0.0065,  0.0202,  ...,  0.0322,  0.0078,  0.0033]],
       device='cuda:0', grad_fn=<DivBackward1>), tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,  1,
        -1, -1,  1, -1, -1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1,  1, -1, -1, -1, -1, -1,  1], device='cuda:0'), 0.1, 1)
(tensor([[ 0.0170,  0.0479, -0.0277,  ..., -0.0149,  0.0134, -0.0117],
        [ 0.0170,  0.0479, -0.0277,  ..., -0.0149,  0.0134, -0.0117],
        [ 0.0170,  0.0479, -0.0277,  ..., -0.0149,  0.0134, -0.0117],
        ...,
        [ 0.0170,  0.0479, -0.0277,  ..., -0.0149,  0.0134, -0.0117],
        [ 0.0170,  0.0479, -0.0277,  ..., -0.0149,  0.0134, -0.0117],
        [ 0.0170,  0.0479, -0.0277,  ..., -0.0149,  0.0134, -0.0117]],
       device='cuda:0', grad_fn=<DivBackward1>), tensor([[-0.0192,  0.0132,  0.0100,  ...,  0.0164,  0.0180,  0.0089],
        [-0.0151, -0.0003,  0.0068,  ...,  0.0429,  0.0102,  0.0013],
        [ 0.0000,  0.0031,  0.0353,  ...,  0.0171,  0.0229, -0.0001],
        ...,
        [-0.0173,  0.0045,  0.0066,  ...,  0.0471,  0.0184, -0.0141],
        [-0.0015,  0.0026,  0.0424,  ...,  0.0253,  0.0280,  0.0036],
        [-0.0192,  0.0033,  0.0191,  ...,  0.0243,  0.0137, -0.0003]],
       device='cuda:0', grad_fn=<DivBackward1>), tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,
         1, -1, -1,  1, -1, -1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1,  1, -1,
        -1, -1,  1, -1, -1, -1, -1, -1], device='cuda:0'), 0.1, 1)
(tensor([[ 0.0169,  0.0478, -0.0277,  ..., -0.0149,  0.0134, -0.0117],
        [ 0.0169,  0.0478, -0.0277,  ..., -0.0149,  0.0134, -0.0117],
        [ 0.0169,  0.0478, -0.0277,  ..., -0.0149,  0.0134, -0.0117],
        ...,
        [ 0.0169,  0.0478, -0.0277,  ..., -0.0149,  0.0134, -0.0117],
        [ 0.0169,  0.0478, -0.0277,  ..., -0.0149,  0.0134, -0.0117],
        [ 0.0169,  0.0478, -0.0277,  ..., -0.0149,  0.0134, -0.0117]],
       device='cuda:0', grad_fn=<DivBackward1>), tensor([[-0.0132,  0.0029,  0.0143,  ...,  0.0227,  0.0055, -0.0012],
        [-0.0005,  0.0015,  0.0181,  ...,  0.0228,  0.0104, -0.0090],
        [-0.0089,  0.0167,  0.0039,  ...,  0.0362,  0.0130, -0.0005],
        ...,
        [-0.0024, -0.0096,  0.0198,  ...,  0.0075,  0.0470, -0.0126],
        [-0.0094,  0.0013,  0.0160,  ...,  0.0200,  0.0106,  0.0006],
        [ 0.0076, -0.0019,  0.0233,  ...,  0.0261,  0.0121, -0.0070]],
       device='cuda:0', grad_fn=<DivBackward1>), tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,  1, -1,
        -1,  1, -1, -1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1,
        -1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1,  1,  1,  1,
        -1, -1, -1, -1, -1, -1, -1,  1], device='cuda:0'), 0.1, 1)
...
```
</details>

I will keep you posted if any error pops up. Thank you

**Comment by nhynes** [comment]
Great! I'll tentatively close this issue. Please feel free to reopen if you encounter any further difficulty.
