### ISSUE TITLE
I got Cuda Error when I run test.py  ,And My soft environment is ubuntu16.04 python3.7 cpu

### ISSUE THREAD

**Issue by pangchao-git** [torralba-lab/im2recipe-Pytorch#35]
/home/pc/anaconda3/envs/py3.7/bin/python /home/pc/work/yq_work/im2recipe-Pytorch/test.py
test begin!
Traceback (most recent call last):
  File "/home/pc/work/yq_work/im2recipe-Pytorch/test.py", line 176, in <module>
    main()
  File "/home/pc/work/yq_work/im2recipe-Pytorch/test.py", line 36, in main
    model = im2recipe()
  File "/home/pc/work/yq_work/im2recipe-Pytorch/trijoint.py", line 102, in __init__
    resnet = models.resnet50(pretrained=True)
  File "/home/pc/anaconda3/envs/py3.7/lib/python3.7/site-packages/torchvision/models/resnet.py", line 261, in resnet50
    **kwargs)
  File "/home/pc/anaconda3/envs/py3.7/lib/python3.7/site-packages/torchvision/models/resnet.py", line 223, in _resnet
    progress=progress)
  File "/home/pc/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/hub.py", line 506, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/pc/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/pc/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/home/pc/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/pc/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "/home/pc/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/serialization.py", line 132, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/pc/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/serialization.py", line 116, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

Process finished with exit code 1

**Comment by jmarintur** [comment]
Hi,

It seems the cached model was serialized when it was in the GPU. Three options: a) You could manually remove the cached file, and let torchvision download it again; b) You could manually (not ideal) change the map_location when you call the cached file; or c) Since you are loading a trained im2recipe model, you could simply put pretrained to False, i.e. resnet50(pretrained=False).

Best,
Javier

**Comment by pangchao-git** [comment]
Thanks. I changed the trijoint.py ,set pretrained = False,But ,Iget the Error
File "test.py", line 179, in <module>
    main()
  File "test.py", line 36, in main
    model = im2recipe()
  File "/home/pc/work/yq_work/im2recipe-Pytorch/trijoint.py", line 121, in __init__
    self.ingRNN_    = ingRNN()
  File "/home/pc/work/yq_work/im2recipe-Pytorch/trijoint.py", line 65, in __init__
    self.embs = nn.Embedding(vec.size(0), opts.ingrW2VDim, padding_idx=0) # not sure about the padding idx 
  File "/home/pc/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 98, in __init__
    self.reset_parameters()
  File "/home/pc/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 109, in reset_parameters
    self.weight[self.padding_idx].fill_(0)
IndexError: index 0 is out of bounds for dimension 0 with size 0

**Comment by jmarintur** [comment]
Check where you put vocab.bin. To provide a different path (default data/vocab.bin) you can indicate it like this: --ingrW2V YOUR/NEW/PATH/vocab.bin
