### ISSUE TITLE
Index error when running test

### ISSUE THREAD

**Issue by leacornelio** [torralba-lab/im2recipe-Pytorch#37]
Hi. I'm trying to run test with the pretrained model but I'm getting this error:

```
Traceback (most recent call last):
  File "test.py", line 173, in <module>
    main()
  File "test.py", line 34, in main
    model = im2recipe()
  File "/home/lea/im2recipe/trijoint.py", line 120, in __init__
    self.ingRNN_    = ingRNN()
  File "/home/lea/im2recipe/trijoint.py", line 65, in __init__
    self.embs = nn.Embedding(vec.size(0), opts.ingrW2VDim, padding_idx=0) # not sure about the padding idx 
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py", line 98, in __init__
    self.reset_parameters()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py", line 109, in reset_parameters
    self.weight[self.padding_idx].fill_(0)
IndexError: index 0 is out of bounds for dimension 0 with size 0

```

**Comment by jmarintur** [comment]
https://github.com/torralba-lab/im2recipe-Pytorch/issues/35#issuecomment-597738083
