### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by someone9388** [torralba-lab/im2recipe-Pytorch#9]
Hi, what do they mean from line 93~ 104 in test.py? I got an error:
File "test.py", line 104, in test                                                                                    
    output = model(input_var[0],input_var[1], input_var[2], input_var[3], input_var[4])                                                                                     
IndexError: list index out of range 

the imput_var seams empty.

**Comment by nhynes** [comment]
Does https://github.com/torralba-lab/im2recipe-Pytorch/issues/7 help solve your problem?

**Comment by amazonzhuyao** [comment]
> Hi, what do they mean from line 93~ 104 in test.py? I got an error:
> File "test.py", line 104, in test
> output = model(input_var[0],input_var[1], input_var[2], input_var[3], input_var[4])
> IndexError: list index out of range
> 
> the imput_var seams empty.

in test.py , add this before "target_var = list()"
input_var.append(v.cuda() if not opts.no_cuda else v)

I'm facing Cuda out of memory issue on AWS P2 instance, and tried replacing "v = torch.autograd.Variable(input[j])" with "v=input[j]" to avoid Variable, but it remains.

Detail info:
Traceback (most recent call last):
  File "test.py", line 187, in <module>
    main()
  File "test.py", line 81, in main
    test(test_loader, model, criterion)
  File "test.py", line 115, in test
    output = model(input_var[0],input_var[1], input_var[2], input_var[3], input_var[4])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/im2recipe-Pytorch/trijoint.py", line 134, in forward
    visual_emb = self.visionMLP(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/models/resnet.py", line 84, in forward
    out = self.conv3(out)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory


Any suggestions would be appreciated.

**Comment by ShinyCode** [comment]
I was just able to get it working by making the batch size in args.py smaller. Try setting it to 1 (instead of 160) in the beginning. I suspect this could be caused by running out of memory from attempting to load too large of a batch on the GPU.
